CREATE TABLE UsersRatings (
	ID BIGINT NOT NULL PRIMARY KEY IDENTITY,
	ReciverID NVARCHAR(450) NOT NULL FOREIGN KEY REFERENCES AspNetUsers(Id),
	SenderID NVARCHAR(450) NOT NULL FOREIGN KEY REFERENCES AspNetUsers(Id)
)